steps:
  - label: ":docker: Build Docker Image"
    command:
      - docker build -t my-node-service .

  - label: ":rocket: Deploy Service"
    command:
      - docker-compose -f compose.yml up -d

  # - label: ":whale: Scale Service"
  #   command:
  #     - docker service scale my-node-service=3  # Scale to 3 instances
