steps:
  - label: ":rocket: Deploy Service"
    command:
      - docker-compose up -d

  # - label: ":whale: Scale Service"
  #   command:
  #     - docker service scale my-node-service=3  # Scale to 3 instances
